.TH INCLUDER 1 "September 2024" "1.0.0" "Includer"

.SH NAME
includer \- Processes template files with includes and frames

.SH SYNOPSIS
.B includer
.RI [options]

.SH DESCRIPTION
Processes template files, replacing @include file@ and @frame frame@ commands with content from external files.
Handles nested includes and frames.

.SH OPTIONS
.TP
\fB-t, --template\fR
Specifies the directory where template files are stored.
.TP
\fB-h, --help\fR
Displays this help message.
